# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9TlTNba88S8LJNdyhVbVkbzj1fLMnz-
"""

import math
import random

# Generate a random angle between 0 and 360 degrees
angle_deg = random.randint(0, 360)

# Convert degrees to radians
angle_rad = math.radians(angle_deg)

# Calculate trigonometric values
sin_value = math.sin(angle_rad)
cos_value = math.cos(angle_rad)
tan_value = math.tan(angle_rad)

# Display results
print("Angle (in degrees):", angle_deg)
print("Sin value:", sin_value)
print("Cos value:", cos_value)
print("Tan value:", tan_value)